service:
  name: bikefinder
  awsKmsKeyArn: arn:aws:kms:us-east-1:704903784842:key/49b8e145-0e10-4e99-a899-c4cdfe07880c

provider:
  name: aws
  runtime: python3.6
  environment:
    CORS_ORIGIN: ${self:custom.${self:custom.stage}.corsOrigin}
    STAGE: ${self:custom.stage}
  iamRoleStatements:
    - Effect: Allow
      Action: ssm:GetParameter
      Resource:
        'Fn::Join':
          - ':'
          - - 'arn:aws:ssm'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - parameter/${self:custom.service.name}/${self:custom.stage}/*
    - Effect: Allow
      Action:  kms:Decrypt
      Resource: ${self:custom.service.awsKmsKeyArn}

custom:
  # work around for ${self:service} not working
  service: ${file(serverless.yml):service}
  # shortcut  to evaluation the various stage sources
  stage: ${opt:stage, self:provider.stage}
  # serverless-finch config
  client:
    bucketName: share.bikehero.io
  # per stage configs
  prod:
    corsOrigin: https://share.bikehero.io
    schedules:
      jump: []
  dev:
    corsOrigin: '*'
    schedules:
      jump:
        - schedule: 'rate(1 minute)'

package:
  include:
    - bikefinder/**/*.py
  exclude:
    - '**/*'

functions:
  cabi:
    handler: bikefinder/handlers.bikeshare_proxy
    events:
      - http:
          path: /cabi
          method: get
  mobike:
    handler: bikefinder/handlers.mobike_proxy
    events:
      - http:
          path: /mobike
          method: get
  limebike:
    handler: bikefinder/handlers.limebike_proxy
    events:
      - http:
          path: /limebike
          method: get
  spin:
    handler: bikefinder/handlers.spin_proxy
    events:
      - http:
          path: /spin
          method: get
  ofo_request_token:
    handler: bikefinder/handlers.ofo_request_token
    timeout: 30
  ofo_login_with_token:
    handler: bikefinder/handlers.ofo_login_with_token
    timeout: 30
  ofo:
    handler: bikefinder/handlers.ofo_proxy
    timeout: 30
    events:
      - http:
          path: /ofo
          method: get
  mbike:
    handler: bikefinder/handlers.mbike_proxy
    timeout: 30
    events:
      - http:
          path: /mbike
          method: get

  jump:
    handler: bikefinder/handlers.jump
    events:
      - http:
          path: /jump
          method: get

  mobike_all:
    handler: bikefinder/handlers.mobike_all
    events:
      - http:
          path: /mobike_all
          method: get

  scrape_jump:
    handler: bikefinder/scraper.scrape_jump
    timeout: 300
    events: ${self:custom.${self:custom.stage}.schedules.jump}

  scrape_mobike:
    handler: bikefinder/scraper.scrape_mobike
    timeout: 300
    #events:
      #- schedule: 'rate(1 minute)'

  search_pattern:
    handler: bikefinder/handlers.search_pattern
    events:
      - http:
          path: /points
          method: get

plugins:
  - serverless-finch
  - serverless-python-requirements
