service:
  name: bikefinder
  awsKmsKeyArn: ${self:custom.cryptKeyId}

provider:
  name: aws
  runtime: python3.6
  environment:
    CORS_ORIGIN: '*' #https://share.bikehero.io/

custom:
  client:
    bucketName: share.bikehero.io
  cryptKeyId: arn:aws:kms:us-east-1:704903784842:key/49b8e145-0e10-4e99-a899-c4cdfe07880c

package:
  include:
    - bikefinder/**/*.py
  exclude:
    - '**/*'

functions:
  cabi:
    handler: bikefinder/handlers.bikeshare_proxy
    events:
      - http:
          path: /cabi
          method: get
  mobike:
    handler: bikefinder/handlers.mobike_proxy
    events:
      - http:
          path: /mobike
          method: get
  limebike:
    handler: bikefinder/handlers.limebike_proxy
    events:
      - http:
          path: /limebike
          method: get
  ofo:
    handler: bikefinder/handlers.ofo_proxy
    timeout: 30
    events:
      - http:
          path: /ofo
          method: get
  mbike:
    handler: bikefinder/handlers.mbike_proxy
    timeout: 30
    events:
      - http:
          path: /mbike
          method: get

plugins:
  - serverless-finch
  - serverless-python-requirements
  - serverless-crypt
